server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://custscwnbepkoq:0d5aac3a50fb04cec4c90753df5bc53f99079a460ba22ddd446eec34c6c3a81a@ec2-54-145-102-149.compute-1.amazonaws.com:5432/d4pnnv1cvu0aa5
    username: custscwnbepkoq
    password: 0d5aac3a50fb04cec4c90753df5bc53f99079a460ba22ddd446eec34c6c3a81a
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Santander / Backend
